### ISSUE TITLE
feature request: use centralized config

### ISSUE THREAD

**Issue by ahmadnassri** [tplk/probot-delete-branch-after-pr-merge#15]
this would be perfect for teams if it also includes centralized configuration through config extension:

https://probot.github.io/docs/extensions/#config

**Comment by tplk** [comment]
It currently uses a fork of probot-config (there was an issues w/ windows build at the moment of writing this app) so it'll be an easy switch.

**Comment by ahmadnassri** [comment]
ah, I see it now (originally just looked in `package.json`) assuming this is released then!

I would then suggest updating the docs to reflect the extendablity :)
